### ISSUE TITLE
Update Manuals to 2.13 and set the tag afterwards

### ISSUE THREAD

**Issue by DavidBlaa** [BEXIS2/Documents#3]
- [x] BAM
- [x] DDM
  - [x] add entity links
- [x] DCM
- [x] DIM
- [x] RPM
  - [x] add missing values to ui / admin section (@MaJoHo )
- [x] SAM
  - [x] reformat to new structure
  - [x] cut images to size of relevant content (currently to large - a lot of "white" area)
  - [x] replace login & add email
  - [x] remove "caution" sentences
  - [x] revise / shortend text
  - [x] remove screenshots with email addresses
- [x] VIM

- [x] check if it is possible to provide an image size

**Comment by geofranzi** [comment]
- [x] https://github.com/BEXIS2/Core/issues/223 check if solved

**Comment by geofranzi** [comment]
Proposed new structure:
A: Overview ->  summary of the module
B: Manual for users -> what a normal user (if he or she have the permission) can do & see
C: Manual for administrators -> all admin tasks (via ui & settings)
